### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by logan-wrld** [noryev/Leto#13]
`
TypeError: Cannot read properties of undefined (reading 'replace')
    at envAll (/Users/loganlentz/Documents/GitHub/leto-gateway/packages/edge-gateway-link/dist/worker.js:5405:52)
    at Object.handle (/Users/loganlentz/Documents/GitHub/leto-gateway/packages/edge-gateway-link/dist/worker.js:2570:26)
    at Object.fetch (/Users/loganlentz/Documents/GitHub/leto-gateway/packages/edge-gateway-link/dist/worker.js:5453:32)
    at /Users/loganlentz/Documents/GitHub/leto-gateway/node_modules/.pnpm/@miniflare+core@2.6.0/node_modules/@miniflare/core/src/standards/event.ts:331:19
    at /Users/loganlentz/Documents/GitHub/leto-gateway/node_modules/.pnpm/@miniflare+shared@2.6.0/node_modules/@miniflare/shared/src/event.ts:29:9
    at EventTarget.<anonymous> (/Users/loganlentz/Documents/GitHub/leto-gateway/node_modules/.pnpm/@miniflare+shared@2.6.0/node_modules/@miniflare/shared/src/event.ts:77:9)
    at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at EventTarget.dispatchEvent (node:internal/event_target:678:26)
    at EventTarget.dispatchEvent (/Users/loganlentz/Documents/GitHub/leto-gateway/node_modules/.pnpm/@miniflare+shared@2.6.0/node_modules/@miniflare/shared/src/event.ts:63:18)
    at EventTarget.dispatchEvent (/Users/loganlentz/Documents/GitHub/leto-gateway/node_modules/.pnpm/@miniflare+shared@2.6.0/node_modules/@miniflare/shared/src/event.ts:87:26)`

**Comment by logan-wrld** [comment]
GATEWAY_HOSTNAME.replace..... 
24 locations...
